version: '3.8'

services:
  holidaykeeper:
#    build:
#      context: .
#      dockerfile: Docker/Dockerfile
    image: seungjusuh/holidaykeeper-service:latest
    container_name: holidaykeeper
    ports:
      - "8080:8080"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./Docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./Docker/prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - holidaykeeper

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1234
    volumes:
      - ./Docker/grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
